### PR TITLE
Code documentation #630

### LINKED ISSUE #630: Finish code documentation
## TODO
* Add API documentation to all classes
* Add some class and component overview documentation to each class and component
* setup JSDoc to work in a nice way with vue component documentation (may need another library)

### PR DESCRIPTION
**Pull request by strinsberg**
Fixes #630

This was branched from the same work that #636 used so it should be merged after that PR.

#### Overview of changes
- Updated the documentation tools to use a template for jsdoc that seems to display things a little better
- Added code doc comments to all classes, components, and modules
- Made a couple small changes to the code to support documentation, or when I found something not being used

Reviewer: @johnanvik

### CODE REVIEW

**Review by johnanvik — COMMENTED** [review]
Documentation is always approved!

**Comment by johnanvik** [comment]
@strinsberg, you can manage the conflicts and merge.

**Comment by strinsberg** [comment]
No problem. I have already dealt with them somewhere else so I know what to do.

**Review by johnanvik — APPROVED** [review]
Documentation.

**Pull request merged**
