### PR TITLE
4 player free for all w/ 3 bots

### PR DESCRIPTION
**Pull request by strinsberg**
Just had an idea for how it would be possible to set up our screen to play with 4 players. In the future it can be extended for making a 2v2 game mode as well, or with some adjustments to the game setup be made to play with up to 4 friends at a time. That is if we actually want to introduce more game modes at all.

Relies on the AI additions for 2.0 in #573, so shouldn't be addressed until that branch is merged.

#### Overview of changes
- Added a third game mode for playing against 3 computer opponents, and a few new default computer players.
- This adds a couple of components to show the screen with 2 or 4 player games differently, while not disrupting other components.
- Added to the message box to make it possible to scroll down and see turn history for AI opponents.
- Added tabs to the stack view area as only one can be shown at a time. This way a player can easily shift to see what stacks other players are building, or hack them.

#### Screen Shots
Screenshot from 2020-06-13 16-04-14
Screenshot from 2020-06-13 16-04-42
Screenshot from 2020-06-13 16-05-31
Screenshot from 2020-06-13 16-06-09

Reviewer: @johnanvik

### CODE REVIEW

**Comment by johnanvik** [comment]
This is really good and is something we'd have needed to address in the near future in any case. I'm adding @hastar07 and @maimoona-bashir as reviewers so they can look this over and comment. Let's discuss this in the meeting tomorrow.

**Comment by strinsberg** [comment]
Sounds good to me. It was just something I was thinking of and cooked up on Saturday for fun. I think with the AI taking time to take their turn this will be much nicer to play. Maybe we can even get all those changes merged into master and then I can pull them back into here before tomorrow so we can see how it improves the play with a little delay. I wasn't really happy with all 3 players taking turns instantly, but it is easily fixable.

**Comment by johnanvik** [comment]
Yes. I sat for a while waiting for them to take their turns to realize they already had.

A thing that would help is for when the player hacks another player, it returns to their tab instead of staying on the opponents. Could file a report for that for the future.

**Comment by johnanvik** [comment]
Perhaps move the free-for-all to above the human. That is the most likely order that people will use.

**Comment by strinsberg** [comment]
Yes that would be good. I think with the waiting this probably won't be an issue as the component will auto switch to each AI play field on their turn and should reset to the players when their turn starts. 

What I really want to get working is a sleep to start their turn of a small amount and then a small sleep afterwards so that the player has time to see the play that the AI made. In 2 player this is easy, but in 4 player not being able to see every play field at once means it will be missed.

**Comment by strinsberg** [comment]
I set things up so that the active player always has their tab visible when it is their turn. This allows the player to start on their play field at the beginning of their turn and also to see the AI play fields as they make their turns, now that we wait a bit before and after they make their moves.

**Comment by strinsberg** [comment]
I have now also added in one of the new card backs that @jsanvik posted on slack. I think it looks way better than the other ones because it is more consistent in style. We can still update it later if we want.

**Comment by maimoona-bashir** [comment]
Scroll_bar
This scroll bar does not work in 4 players layout. It works fine in 2 players mode.
In 4 Players, it has to scroll from a certain (not normal) position to make it work.

**Comment by hastar07** [comment]
Ok from my side 👍

**Comment by maimoona-bashir** [comment]
Issue resolved.

**Pull request merged**
